package stormairline.utils;

import java.util.ArrayList;
import java.util.HashMap;


public class DestinationHashmap {

  HashMap<String, ArrayList<String>> multimap =
      new HashMap<String, ArrayList<String>>();

  public HashMap<String, ArrayList<String>> getMultimap() {
    ArrayList<String> listAmbon = new ArrayList<String>();
    listAmbon.add("AMQ");
    multimap.put("Ambon", listAmbon);
    ArrayList<String> listAmsterdam = new ArrayList<String>();
    listAmsterdam.add("AMS");
    multimap.put("Amsterdam", listAmsterdam);
    ArrayList<String> listBalikpapan = new ArrayList<String>();
    listBalikpapan.add("BPN");
    multimap.put("Balikpapan", listBalikpapan);
    ArrayList<String> listBandaAceh = new ArrayList<String>();
    listBandaAceh.add("BTJ");
    multimap.put("Banda_Aceh", listBandaAceh);
    ArrayList<String> listBandarLampung = new ArrayList<String>();
    listBandarLampung.add("TKG");
    multimap.put("Bandar_Lampung", listBandarLampung);
    ArrayList<String> listBandung = new ArrayList<String>();
    listBandung.add("BDO");
    multimap.put("Bandung", listBandung);
    ArrayList<String> listBangkok = new ArrayList<String>();
    listBangkok.add("BKK");
    multimap.put("Bangkok", listBangkok);
    ArrayList<String> listBanjarmasin = new ArrayList<String>();
    listBanjarmasin.add("BDJ");
    multimap.put("Banjarmasin", listBanjarmasin);
    ArrayList<String> listBanyuwangi = new ArrayList<String>();
    listBanyuwangi.add("BWX");
    multimap.put("Banyuwangi", listBanyuwangi);
    ArrayList<String> listBatam = new ArrayList<String>();
    listBatam.add("BTH");
    multimap.put("Batam", listBatam);
    ArrayList<String> listBauBau = new ArrayList<String>();
    listBauBau.add("BUW");
    multimap.put("Bau-Bau", listBauBau);
    ArrayList<String> listBeijing = new ArrayList<String>();
    listBeijing.add("PEK");
    multimap.put("Beijing", listBeijing);
    ArrayList<String> listBengkulu = new ArrayList<String>();
    listBengkulu.add("BKS");
    multimap.put("Bengkulu", listBengkulu);
    ArrayList<String> listBima = new ArrayList<String>();
    listBima.add("BMU");
    multimap.put("Bima", listBima);
    ArrayList<String> listDenpasar = new ArrayList<String>();
    listDenpasar.add("DPS");
    multimap.put("Denpasar", listDenpasar);
    ArrayList<String> listGorontalo = new ArrayList<String>();
    listGorontalo.add("GTO");
    multimap.put("Gorontalo", listGorontalo);
    ArrayList<String> listGuangzhou = new ArrayList<String>();
    listGuangzhou.add("CAN");
    multimap.put("Guangzhou", listGuangzhou);
    ArrayList<String> listGunungSitoli = new ArrayList<String>();
    listGunungSitoli.add("GNS");
    multimap.put("Gunung_Sitoli", listGunungSitoli);
    ArrayList<String> listHongKong = new ArrayList<String>();
    listHongKong.add("HKG");
    multimap.put("Hong_Kong", listHongKong);
    ArrayList<String> listJakarta = new ArrayList<String>();
    listJakarta.add("CGK");
    multimap.put("Jakarta", listJakarta);
    ArrayList<String> listJambi = new ArrayList<String>();
    listJambi.add("DJB");
    multimap.put("Jambi", listJambi);
    ArrayList<String> listJayapura = new ArrayList<String>();
    listJayapura.add("DJJ");
    multimap.put("Jayapura", listJayapura);
    ArrayList<String> listJember = new ArrayList<String>();
    listJember.add("JBB");
    multimap.put("Jember", listJember);
    ArrayList<String> listKendari = new ArrayList<String>();
    listKendari.add("KDI");
    multimap.put("Kendari", listKendari);
    ArrayList<String> listKualaLumpur = new ArrayList<String>();
    listKualaLumpur.add("KUL");
    multimap.put("Kuala_Lumpur", listKualaLumpur);
    ArrayList<String> listKupang = new ArrayList<String>();
    listKupang.add("KOE");
    multimap.put("Kupang", listKupang);
    ArrayList<String> listLabuhanBajo = new ArrayList<String>();
    listLabuhanBajo.add("LBJ");
    multimap.put("Labuhan_Bajo", listLabuhanBajo);
    ArrayList<String> listLanggur = new ArrayList<String>();
    listLanggur.add("LUV");
    multimap.put("Langgur", listLanggur);
    ArrayList<String> listLhokSeumawe = new ArrayList<String>();
    listLhokSeumawe.add("LSW");
    multimap.put("Lhok_Seumawe", listLhokSeumawe);
    ArrayList<String> listLuwuk = new ArrayList<String>();
    listLuwuk.add("LUW");
    multimap.put("Luwuk", listLuwuk);
    ArrayList<String> listMalang = new ArrayList<String>();
    listMalang.add("MLG");
    multimap.put("Malang", listMalang);
    ArrayList<String> listMamuju = new ArrayList<String>();
    listMamuju.add("MJU");
    multimap.put("Mamuju", listMamuju);
    ArrayList<String> listManado = new ArrayList<String>();
    listManado.add("MDC");
    multimap.put("Manado", listManado);
    ArrayList<String> listManokwari = new ArrayList<String>();
    listManokwari.add("MKW");
    multimap.put("Manokwari", listManokwari);
    ArrayList<String> listMedan = new ArrayList<String>();
    listMedan.add("KNO");
    multimap.put("Medan", listMedan);
    ArrayList<String> listMelbourne = new ArrayList<String>();
    listMelbourne.add("MEL");
    multimap.put("Melbourne", listMelbourne);
    ArrayList<String> listMerauke = new ArrayList<String>();
    listMerauke.add("MKQ");
    multimap.put("Merauke", listMerauke);
    ArrayList<String> listOsaka = new ArrayList<String>();
    listOsaka.add("KIX");
    multimap.put("Osaka", listOsaka);
    ArrayList<String> listPadang = new ArrayList<String>();
    listPadang.add("PDG");
    multimap.put("Padang", listPadang);
    ArrayList<String> listPalangkaraya = new ArrayList<String>();
    listPalangkaraya.add("PKY");
    multimap.put("Palangkaraya", listPalangkaraya);
    ArrayList<String> listPalembang = new ArrayList<String>();
    listPalembang.add("PLM");
    multimap.put("Palembang", listPalembang);
    ArrayList<String> listPalu = new ArrayList<String>();
    listPalu.add("PLW");
    multimap.put("Palu", listPalu);
    ArrayList<String> listPangkalPinang = new ArrayList<String>();
    listPangkalPinang.add("PGK");
    multimap.put("PangkalPinang", listPangkalPinang);
    ArrayList<String> listPekanbaru = new ArrayList<String>();
    listPekanbaru.add("PKU");
    multimap.put("Pekanbaru", listPekanbaru);
    ArrayList<String> listPerth = new ArrayList<String>();
    listPerth.add("PER");
    multimap.put("Perth", listPerth);
    ArrayList<String> listPontianak = new ArrayList<String>();
    listPontianak.add("PNK");
    multimap.put("Pontianak", listPontianak);
    ArrayList<String> listPraya = new ArrayList<String>();
    listPraya.add("LOP");
    multimap.put("Praya", listPraya);
    ArrayList<String> listPutussibau = new ArrayList<String>();
    listPutussibau.add("PSU");
    multimap.put("Putussibau", listPutussibau);
    ArrayList<String> listSabang = new ArrayList<String>();
    listSabang.add("SBG");
    multimap.put("Sabang", listSabang);
    ArrayList<String> listSaumlakiYamdena = new ArrayList<String>();
    listSaumlakiYamdena.add("SXK");
    multimap.put("Saumlaki-Yamdena", listSaumlakiYamdena);
    ArrayList<String> listSemarang = new ArrayList<String>();
    listSemarang.add("SRG");
    multimap.put("Semarang", listSemarang);
    ArrayList<String> listSeoul = new ArrayList<String>();
    listSeoul.add("ICN");
    multimap.put("Seoul", listSeoul);
    ArrayList<String> listShanghai = new ArrayList<String>();
    listShanghai.add("PVG");
    multimap.put("Shanghai", listShanghai);
    ArrayList<String> listSibolga = new ArrayList<String>();
    listSibolga.add("FLZ");
    multimap.put("Sibolga", listSibolga);
    ArrayList<String> listSingapore = new ArrayList<String>();
    listSingapore.add("SIN");
    multimap.put("Singapore", listSingapore);
    ArrayList<String> listSolo = new ArrayList<String>();
    listSolo.add("SOC");
    multimap.put("Solo_City", listSolo);
    ArrayList<String> listSorong = new ArrayList<String>();
    listSorong.add("SOQ");
    multimap.put("Sorong", listSorong);
    ArrayList<String> listSumbawa = new ArrayList<String>();
    listSumbawa.add("SWQ");
    multimap.put("Sumbawa", listSumbawa);
    ArrayList<String> listSurabaya = new ArrayList<String>();
    listSurabaya.add("SUB");
    multimap.put("Surabaya", listSurabaya);
    ArrayList<String> listSydney = new ArrayList<String>();
    listSydney.add("SYD");
    multimap.put("Sydney", listSydney);
    ArrayList<String> listTanjungPandan = new ArrayList<String>();
    listTanjungPandan.add("TJQ");
    multimap.put("Tanjung_Pandan", listTanjungPandan);
    ArrayList<String> listTanjungPinang = new ArrayList<String>();
    listTanjungPinang.add("TNJ");
    multimap.put("Tanjung_Pinang", listTanjungPinang);
    ArrayList<String> listTanjungRedep = new ArrayList<String>();
    listTanjungRedep.add("BEJ");
    multimap.put("Tanjung_Redep", listTanjungRedep);
    ArrayList<String> listTaraken = new ArrayList<String>();
    listTaraken.add("TRK");
    multimap.put("Taraken", listTaraken);
    ArrayList<String> listTernate = new ArrayList<String>();
    listTernate.add("TTE");
    multimap.put("Ternate", listTernate);
    ArrayList<String> listTimika = new ArrayList<String>();
    listTimika.add("TIM");
    multimap.put("Timika", listTimika);
    ArrayList<String> listTokyo = new ArrayList<String>();
    listTokyo.add("HND");
    listTokyo.add("NRT");
    multimap.put("Tokyo", listTokyo);
    ArrayList<String> listUjungPandang = new ArrayList<String>();
    listUjungPandang.add("UPG");
    multimap.put("Ujung_Pandang", listUjungPandang);
    ArrayList<String> listYogyakarta = new ArrayList<String>();
    listYogyakarta.add("JOG");
    multimap.put("Yogyakarta", listYogyakarta);

    return multimap;
  }

  public void setMultimap(HashMap<String, ArrayList<String>> multimap) {
    this.multimap = multimap;
  }

}